include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart

linter:
  rules:
    prefer_const_constructors: false
    file_names: false
    library_prefixes: false
    avoid_print: false